// // yaha apn what is ProcessSynchronization dekhenge, processSynchronization na hone k disadvantages(mtlb jaise race-condition-problem , variable-inconsistency-problem, variable-mis-Match etc..etc..) and processSynchronization k na hone advantages dekhenge.
// and but sbse phle apn Process-Types dekhenge as q ki processSynchronizatio ki need Coperative-Type-of-Processes meh aati hai.

// process-synchronization ka  mtlb ki processes ka synchronization,  mtlb jab multiple processes(coperative-processes) ka eksaat chalti/execute hoti hai then vaha kafi sari problems create ho skti hai, only-and-only bcoz of sharing of resources(like jaise: variables,code,resources..), then mtlb toresolve these problems apnko enn Processes ko synchronize(mtlb processes ka taal-mel) krna hota hai takki yeh problems na hove.

// (processes ka eksaaat chlne ka mtlb ki ek processor meh toh ekbaar meh ek hi process chlti hai, but yaha eksaat ka mtlb ki ek process toh cpu meh execute hogi and baki processes ready-queue meh hogi and then as per "time-quantum" and "pre-emptiveness" processes cpu meh chlti hai and esiko apn processes ko eksaat chlna khtehh hai or ya mtlb multitasking khtehh hai. )
// tip:-
// os meh basically apn processes/programs ki execution-starting se leke executing-ending tk ka padhtehh hai. ki mtlb jab process/program ko double-click krke start kiya jata hai tb vaha se leke process/program ki ending tk bich meh kya-kya hota hai, mtlb operating-system uss/unn single ya multiple requested processes/programs ko kaise execute krvata hai voh sab apn operating-system meh dekhtehh hai. so toh sbse phle toh apn simply-simply upr-upr se yeh dekhenge ki: os ki defination, os k functions ,types of os , Process-States Diagram mtlb jab os process/program ko execute krta hai then os process ko kin-kin State meh rkhta hai during its whole execution. phir system-call ka concept ki os se baat sirf system-call se hoti hai, phir user-mode and kernel-mode mtlb ki os enn two-modes meh kaam krta hai and os apne-app ko enn two-modes meh switch krta rheta hai, jaise mtlb ki user-mode meh os user-se-communicate krta hai and kernel-mode meh aake os computer-hardware-resources se communicate krta hai. phir aata hai concept of "process" and "thread" and phir multiprocessing and multithreading, mtlb ki jab ek hi process/program baar-baar execute hone ki request aajati hai then vaha mutliprocing and multithreading ka concept use hota hai for executing that same-processes.
// jaise jab processes/programs ka requested to run/execute then sbse phle toh Os uss process/program ko Ram meh "queue" meh load krta hai then "ready-queue" load krta hai and then phir ready-queue se cpu meh load krta hai, so toh yaha cpu meh "ready-queue" se load krne ko "process-scheduling/Cpu-scheduling" khtehh hai, and mtlb yaha kuch algorithms/methods/protocols/rules follow hotehh hai for loading the process from the processes-in-readyqueue into the cpu. so toh mtlb apn Os meh apn enn process-scheduling-algorithms k bareh meh bhi pdtehh hai.
// and after jab cpu meh process-schedule ho jati hai then concept aata hai of process-synchronization mtlb multiple-processes ko cpu meh ek-saat chalana. toh mtlb apn yaha yeh dekhtehh hai ki multiple-processes cpu meh ek saat kaise chlti hai.
// and then after this concept aata hai about "Deadlock" , mtlb ki jab process-scheduling(mtlb process ko cpu nhi mil rha ho) nhi ho pa rhi ho, bcoz of waiting-time and cpu-usage inconsistency.
// and then phir baat aati hai memory-management ki jaise cpu meh koi processes hai and unko memory-access krni hai then voh memory kaise krne k algorithms/methods/protocols/rules kya and kaise hotehh hai.
// and then apn phir os kuch additional functionalties dekhenge jaise.. hardisk-architecture, file-system-architecture , and then protection-security.