// Array-intro:
// As NOw YAHA pe apn Array-intro dekhenge, as esseh toh apn "Array" k bareh meh janteh hai, but ek baar chota-sa, shortly Array ko vapis se acche se dekhenge..
// As toh now apn Array ki defination mtlb Array kya hota hai phle yeh dekhenge and then Array-defination mtlb Array-declaration and Array-intialization dekhenge and then phir dheere-dheeere sab cheeze dekhenge..

// Array-defination:
// As in simple language "array" ka mtlb hota hai ki "collection of mutiple-items of same type" , thus toh yaha computer-programming meh bhi Array ka mtlb bhi yahi hota hai bas thoda yaha items ka difference hai, mtlb yaha items hai single-variable-containers(not "Node" sirf simple-single-variable-container). so thus toh..
//"Array" is collection of single-variables-containers, and where yeh single-variabel-containers contiguous hoteh hai mtlb unke addresses- sequence meh hoteh hai jaise 204, 208 , 212 and soo..on upto size of array. and or apn orr simply esseh bhi bol skteh hai ki "Array" is a collection of variables.. , whereas-notepoint ki yeh single-varialble-container ko apn ""single-valued-container"" bhi bolteh hai and aur "scalar-variable-container" bhi bolteh hai.. as apn esko scalar essliy bol rahe hai q ki ess container meh only ek hi value hai , ek hi cheeze mtlb value k saat meh orr koi cheeze nhi hai jaise "direction" etc.. etc.. but as programming meh "pointers" hoteh hai "direction" ki jagah.. and toh mtlb jin container meh "values" and "pointers" usseh apn "Node" bolteh hai or comonly "Vector" bhi bol deteh hai. and jis container meh only "values" mtlb "values-containers" hoteh hai usko apn "Array" bolteh hai, but majorly and commanly not in terms of memory "Array" ko collection of values bol diya jata hai , but in actual Array is collection of containers where voh containers can be sclar-container or vector-container or Node etc..etc.. and yeh actual wali cheez memory-ki-terms meh define huee hai. and apn mtlb ajay as a programmer programming-concept ko dono tarah se dekhteh and define krteh hai, mtlb phle in terms of memory dekhteh , samajteh hai and then phir comman-general bhasa meh dekhteh hai and define krteh hai. and yeh dono hi bohat-bohat jaruri hai, important hai.

// note-point: as toh values nhi hoti , actual meh Containers hoteh hai . and unn Containers meh values hoti hai. as toh hamesa apnko "Containers" ki terms meh hi sari cheeze sochni hai..

// As toh NOw aab aage apn Array-declaration dekhenge and Array-Intialization bhi dekhenge...

// note-point:-
// Array-declaration:
// as toh jab Array-declare hota hai then mtlb vaha phle ek single-container allocate hota hai and uska naam given k equal hota hai and then uss single-bade-parent container meh chote-chote container allocate hoteh hai and unn containers ka naam hota hai name[0] , name[1] etc..etc.. toh mtlb apn unko unke naam se access kr skteh hai..
// and toh memory ki terms meh boleh toh as toh jab apn koi bhi vector-container declare krteh hai then vaha phle ek-single-parent-container allocate hota hai and usmeh phir sub-vector-or-scalar-containers allocate hoteh hai. and enn parent and parent-meh-Sub-containers k bhi naam hoteh hai. jaise array meh provided-name parent-container ko mil jata hai and sub-containers ki naming yeh essi hoti hai:- arrayname[0] , arrayname[1] ...etc.etc..  and jaise "classes" k liyeh toh declaration meh provided-name toh parent-container ka name hota hai and baki-sub-containers ka name toh jo apn class-design-defination meh provide krteh hai vohi hi hota hai.
