//🔥💲 AS toh Now YAHA pe apn "Full" and "Complete" binary-tree k bareh meh dekhenge ki mtlb "Full-binary-tree" kya hoteh hai and yeh "Complete-binary-tree" kya hotehh hai. 💲🔥

//🔔🔔1. as toh phle apn "Full-binary-tree" k bareh meh dekhenge: 🔔🔔
// thus toh "Full-binary-tree" voh binary-tree hota hai jiski particular-height pe maximum-nodes contained hoteh hai, present hoteh hai,so then that "binary-tree" is called as "Full-binary-tree".
// and formulatically boleh toh voh tree jiske "no.-of-nodes" n = 2^(h+1)-1 hoteh hai. where here "n" is no,.-of-nodes and "h" is height-of-binary-tree

//🔔🔔2. and now apn "Complete-binary-tree" k bareh meh dekhenge: 🔔🔔
// as "Complete-binary-tree" voh "binary-tree" hota hai jisko "array" meh represent krne par uss array meh koi "gap-nhi-rheta" ,thus then that "binary-tree" is called as "Complete-binary-tree". and agr koi gap rahera hai, then that "binary-tree" will not be a "Complete-binary-tree".
// and now agr apn "book-defination-of-complete-binary-tree" ki baat kare then book-defination k according "complete-binary-tree" voh tree hota hai jiski (h-1)-height of the-binary-tree toh "full-binary-tree" hota hai and phir last-level of the "binary-tree" ko left-to-right fill kiya jata hai, and left-to-right k bich meh agr koi gap nhi rheta then that "binary-tree" is called as or known as "Complete-binary-tree".
//👿📔imp-Note-point:-as apn ek baat note krenge ki apn yeh "complete"-word ka use kr rahe hai voh in the sense-of-array kr rahe hai ki array complete hai ya nhi hai, whereas complete ka mtlb ki array meh koi "gap" hai ya nhi hai. as agr array meh koi "gap" nhi hai then that "array" is "complete-array" and array meh agr koi gap(mtlb blank-space or mtlb empty-element) hai then that "array" is not "complete-array". thus toh "in-complete-tree"  array-representation k liyeh suitable nhi hai, mtlb apn "in-complete-tree" ko array meh represent nhi kr sktehh, q ki voh phir sahi nhi rhega q ki vaha phir uss array meh gaps rhenge, and thus toh phir gaps ko find-out krne k liyeh apnko alg se phle kaam krna hoga and then baad meh apn apna actual operation kr payenge uss "tree" pe. thus toh allover apnko yeh wali baat dhyn meh rkhni hai.

//👿📔imp-Note-point-1:- as toh ek important baat note krenge ki "Full-binary-tree" is simultaneously "Complte-binary-tree" bhi hota hai. but eska vice-versa nhi hai,  mtlb ki "complete-binary-tree" jaruri nhi hai ki voh "full-binary-tree" hoga hi mtlb voh ho bhi skta hai and nhi bhi ho sktaa. but "full-binary-tree" hamesa "complete-binary-tree" hota hi hai. 👿📔