// YAHA pe apn DATA-Strucutues and Algorithms k bareh meh dekhenge:
// 🌟as Data-structure mtlb "data k liyeh Structure" mtlb data ko store krne k liyeh "memory meh Structure" , mtlb memory meh data-store k liyeh memory-parts allocate krna ek tarike se mtlb overall memory meh ek structure banana for storing the data , and that Structure in memory for storing data usko apn simply , pyaar se Data-Structure khteh hai.
// as Data-structure mtlb ek structure for storing the data , and after storing accessing the data as mtlb ess structure meh kafi sare tarike , rasteh hoteh hai jinseh apn phir stored data ko very-fastly and smoothly access bhi kr skteh hai.
//
// and yaha pe apn Data-Structure banana nhi dekhenge , as apn toh kuch bane-banayeh data-structures ko dekhenge ki enn data-structure ka structure(mtlb memory-structure) kaisa hota hai mtlb esa hota hai and phir yeh data-structure kis tarah kaam krta hai , and apnko phir yeh idea lag jayega ki apn ess kisi particular data-structure ko kaha use kr skteh hai. takki apnko asani ho programs ko banane meh and programs k andar code krne meh mtlb code-tokens ko access krne meh.
// toh sbse phle apn define krenge ki yeh Data-Structures and Algorithms kya hoteh hai mtlb enka kya mtlb hota hai and enka kaha use hota hai. 🌟

// Data-Structures simply means ki Data ko Structure krna memory meh takki apna programm efficient bane mtlb uski performance high ho.. as like: jaise apn int a , float b , static int a , global char c etc..etc.. jo bhi kuch krteh hai , unn sabko apnko kafi acchi tarah se memory meh allocate krna hota hai , mtlb apnko vaha unn Container-data ko dynamically bhi allocate krna hota in heap and stack ..etc..etc.. mtlb ek intelligent way meh Data- ko memory meh allocate krna ya Structure krna hi Data-Structures khelata hai. khne ka mtlb hai ki haan bane-bane Data-structure meh esseh hi hota hai , mtlb enn cheezo ko dekh kr hi voh data-structure banaye gayeh hai. thus toh bas apnko yeh bane-banyeh huee data-structure dekhne hai , and phir enn data-sturctures ko apnko apne Algorithms meh apply krna hai. thust toh apne program ek dam mast program ban jayega.

// Algorithm simply ek tarika hota hai mtlb ek-bundle ya Queue of steps hoti hai kisi kaam ko krne ka, jaise apn ek program banateh jo user se input leta hai koi html-code and phir voh user ko sirf-html-content deta hai, thus mtlb esa Program kaise banaya jayeh mtlb esa Program banane k liyeh apnko kuch koi tarika soch na hoga mtlb ess program ko apnko chote-chote chukde meh break krna hoga mtlb chote-chote Steps meh krna hoga , sochna hoga. ese Program ko banane k liyeh . thus toh yaha pe yeh tarika mtlb Steps ko hi simply Programming meh Algorithm bolteh hai ya bol dete hai.
//  as Computer- k accoding Algorithm is a set of Steps that is made or designed for making a Program(computer-program) mtlb kisi Program banane k liyeh jo Steps liyeh jati hai unhi steps ko simply Algorithm bolteh mtlb voh ek tarika jisseh voh esa Program ya software ban skta hai.

// Algorithm mtlb voh steps jo apn banateh hai , ya decide krteh hai kisi kaam ko krne k liyeh . unn allover sbhi steps k combination ek Algorithm bola jata hai.

// note-point: As apna Algorithm itna accha hona chahiyeh ki voh kisi kaam mtlb Program ko ya Program k sub-part ko kafi acche se mtlb minimum-time meh and acurately pura krde mtlb program minimum-time and accutrately khatam hojayeh. as kisi Kaam ko krne k liyeh ek Accha Algorithm hona chahiyeh and Acche Algorithm banane k liyeh ek accha and kaam-k-respecitve Data-Structure chahiyeh hota hai , mtlb ek acchi data-Structuring mtlb memory meh data ki structing bhi honi hoti hai.
// note-point: as kisi Kaam ko krne k liyeh bohat sare Algorithm hoteh hai, but allover apnko voh Algorithm choose and follow krna hai , jo ki apne Program ko high-performance deta ho , mtlb uss algorithm se apna program highly-perfomable krta ho. and yeh baat apn aage orr acche clear krna sikh jayenge mtlb , apn Algorithms ko unke  🌟 "Asymtotic-notations" 🌟  ko dekh kr samaj jayenge ki konsa Algorithms apnko follow krna chahiyeh.
// thus toh mtlb apnko kafi acche se Data-Structing bhi aani chahiyeh (where Data-structing mtlb acche se acche and accordingly Data-structure ka use krna) and phir apna Logic(mtlb tarike) mtlb kisi kaam ko krne k liyeh jo steps apn sochenge ya sochteh hai voh bhi acche hone chahiyeh mtlb voh kaam krne chahiyeh and and jo bhi tarika mtlb jo bhi steps apn lenge (mtlb Algorithm ) voh accha hona chahiyeh and voh steps apnko Data-structing ko dhyan meh rkhteh huyeh krne hai , bcoz Ek accha Algorithm mtlb usmeh ek acche dataStructures bhi use kiyeh gayeh hai. tabhi apna tarika mtlb apne steps mtlb apna "Algorithm "kafi accha, fast and high performance meh kaam karega.
// as yeh upar wali sare baateh apnko acche se dhyn rkhni hai bcoz esseh apn data-structure ka mtlb and use and prequisites samaj lenge , toh mtlb yeh ekdam -mastam baat ho jayegi.

//🌟 thus toh allover apn Data-structure and Algorithms ka use krke kafi acche and efficient likh skteh hai. as toh mtlb Ds-algo ka yahi kaam hota hai ki apn kafi acche program bana sake.. or mtlb yeh Coding se koi alag cheez nhi hai.

// 👍Memory Layout of C-Program:
// mtlb jab koi C-program memory meh load hota hai toh, vaha uss program k liyeh memory meh ek-memory-part alot hota hai ess program ko load hone k liyeh. now aab ek ess memory-part meh 4- diff-diff size k alag-alag memory-parts allocate hoteh hai:
/*  1.code-block (ess memory-part-container meh code.exe machine-level code load hota hai.)
    2.global-variable and static-variable block (ess memory-container meh jo global-and static variable-containers ess memory-part meh load hoteh hai.)
    3.stack (now Functions and their content k liyeh jo memory allocate ki jati hai voh ess memory-part meh allocate hoti hai. and yeh functions and content ka allocate hona dynamic hai mtlb ek baar function k a kaam hogaya mtlb function end hogaya then phir ess fucntion k liyeh allocate memory vapis se disallocate ho jati hai and phir vapis se ess function ka parent-function ka content serial run hota hai , and ek baar yeh function end hogaya toh ess function k liyeh allcoated memory disallocate hojayegi , and phir vapis se eska parent-function resume hojayega. as yeh function stop ess liyeh huaa that q ki ess function meh koi orr function call huaa thaa thus serial-wise k according uss function ko stop hona hota hai and phir esske andar call huyeh function k liyeh stact meh hi dusri alag se memory allocate hoke uska kaam krvake and return krvake phir voh vapis se disallocate ho jata hai , and yeh process sbhi function and unke child-functions and unke bhi child-function and sooo..onn sbhi k liyeh yeh eski tarah memory allocation and disallocation hota hai. ) note-point: and jaise jab yeh stack fully bhar jata hai mtlb koi vaha pe memory-dissallocation nhi hota hai . then ess state ko "Stackoverflow" khteh hai.
    4.heap   (heap me sirf Dynamic-memory-containers hi allocate hote hai. jo ki malloc and calloc function se allocate kiyeh jateh hai.)
*/