
// As mtlb apn Undirected graph ko banana dekhenge... mtlb phle kisi other-form meh represent krna dekhenge... and then uss form meh hi memory-meh usko store krenge....
// As mtlb apn banana nhi abhi only representing krna dekhenge ki apn jaise apn 2d-array ko as a matrix represent krteh hai, toh mtlb apnko usko samajna and uspeh kaam karna aasaan easy ho jata hai...